Feat/in 88 Prefill
aleemer/Internify pull request #72
Opened 2021-07-29 23:00 UTC by JudeShamsi

#### User Story
Add the user story number here.
https://chaosneutral.atlassian.net/jira/software/projects/IN/boards/1?selectedIssue=IN-88

#### Changes made
Describe the changes made in this PR.
- added prefill page

#### Does your new code introduce new warnings on dev console?
Yes/No.
No
#### Test Steps
Describe the test steps to test your changes.
navigate to /prefill

2021-07-29 23:48 UTC, tommytwm requested changes
Looks great! You need to make the Create button in the Profile page direct to the Prefill page, then make the new posting button direct to the original Create page. Also, the footer is not anchored at the bottom of the page. I think you should able toggle this by passing in `absolute={true}` attribute to the footer.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/37882255/127579434-8b43e409-b049-4a6f-b817-30fcdbe3263d.png">

2021-07-30 01:27 UTC, ReneReid commented
I just love this so much!!

2021-07-30 01:27 UTC, ReneReid approved these changes

2021-07-30 04:07 UTC, tommytwm approved these changes

2021-07-30 17:16 UTC, aleemer approved these changes
It's awesome, I love it!

2021-07-30 20:47 UTC, merged