Feat/in84 create edit job page 2
aleemer/Internify pull request #87
Opened 2021-08-03 22:01 UTC by ReneReid

**User Story**
IN-84 Create Edit Page
https://chaosneutral.atlassian.net/browse/IN-84

**Changes made**
The user can now (partially) edit a previously created job posting. (Note editing functionality is not fully completed, as @JudeShamsi has offered to work on the radiobuttons, checkboxes. )

To do so, I have created a new page called "Edit.js", found within src->components-> pages

Edit.js, as much as possible, utilizes the components that are also used by "Create.js"; these components had to be modified to reflect whether the user is editing vs creating a job. Thus now the components work equally well whether you are creating a job or editing a job.

In addition, to reduce code duplication as much as possible, a series of functions have been extracted out that would otherwise exist in both Create.js and Edit.js. These functions are now contained within src -> effects -> filter.effects.js
Note that though filter.effects.js contains many functions, the vast majority of these are helper functions; only 2 need be exported.

Also note that one function that is common between Edit.js and Create.js was not extracted out - updateStore() found on line 92 of Edit.js and line 118 of Create.js. The reason this was not extracted is because this function relies on quite a few variables that are defined in Edit.js/Create.js; extracting it would have required a very large argument list, and so to avoid creating a function with such a large argument list, I kept that function in Edit.js/Create.js

Separately, a job edit route has been created (connects to our mongoDB database), and a job update action.

Next steps: @JudeShamsi will be fixing up the radiobuttons and checkboxes, and update the registered keys so that the Edit page is correctly populated.

**Does your new code introduce new warnings on dev console?**
Yes - See below (and attached picture) for text. I believe this warning will resolve itself once @JudeShamsi has finished working on radiobutton/ checkbox editing. I can further explain with a demonstration as to why this is my belief.

"Warning: Encountered two children with the same key... Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted - the behavior is unsupported and could change in a future version"

**Test Steps**
- get the website running
- log in with a user's account
- click on an existing job (once you are on profile page)
- click "Edit" on the upper right
- make edits
- verify edits made by going to profile page, clicking on the job edited, and viewing it
- can also check our database using Postman to verify that the job has indeed been edited

![image](https://user-images.githubusercontent.com/65432928/128091971-efef5bc1-b36f-4026-a20f-d8529365edb3.png)

#### Test Steps
Describe the test steps to test your changes.

2021-08-05 23:07 UTC, JudeShamsi reviewed
Added following changes: 

- brought in my checkbox/radio button state code from develop so all postings have their full job state populated
- removed the call to PUT in updateStore() bc it was overloading the server and calling the PUT request every time we clicked continue,
- re-did the jobs.put() API logic
- removed the editJob() action, type and logic in the reducer bc it wasn't updating the state initially and we dont need to update store
- removed the second GET/jobId call in Edit.js bc we already call GET/jobId when we get to View.js, so now populating the jobs store 'currentPosting' object and Edit.js is just getting the jobdata from there. Reduces unneeded duplicate call to backend
- fixed race condition in Create and Edit with getStudents()
- fixed checkbox and radio btn state for Edit jobs by forcing a re-render trigger on the components with useState

2021-08-06 00:54 UTC, tommytwm requested changes
Looks good, just a couple of changes/fixes are required:

When I click continue without changing anything, the registered keys doesnt update:
<img width="1054" alt="image" src="https://user-images.githubusercontent.com/37882255/128439627-22b72305-c23f-47d8-b63a-4747679c6b3a.png">


Change the edit button to say 'Update':
<img width="529" alt="image" src="https://user-images.githubusercontent.com/37882255/128439552-59901586-58d6-4b57-a37e-1710eeebd853.png">

2021-08-06 00:54 UTC, tommytwm commented on backend/routes/api/matches.js
> +  // res.status(200).json("done");
Remove comment

2021-08-06 01:53 UTC, tommytwm approved these changes

2021-08-06 01:54 UTC, aleemer approved these changes

2021-08-06 02:01 UTC, merged